snowflake-dw:
    target:dev
    outputs:
      dev:
        type: snowflake
        account: xxb15188.us-east-1

        # User/password auth
        user: AIRBYTE_USER
        password: password

        role: AIRBYTE_ROLE
        database: AIRBYTE_DATABASE
        warehouse: AIRBYTE_WAREHOUSE
        schema: AIRBYTE_SCHEMA
        threads: 1
        client_session_keep_alive: False
        query_tag: dbt-q

        # optional
        connect_retries: 0
        connect_timeout: 10
        retry_on_database_errors: False
        retry_all: False